export const mock_StationModal = [{
  "id": 163605,
  "code": null,
  "name": "coordinate",
  "title": "经纬度",
  "sn": 5,
  "dataType": {"id": 163252, "code": null, "name": "position", "title": "position(位置)", "sn": 10, "activity": true, "baseType": false},
  "type": 1,
  "symbol": null,
  "validationType": null,
  "unit": null,
  "boolValues": null,
  "enumValues": null,
  "min": -180,
  "max": 180,
  "step": 1e-10,
  "length": null,
  "timeAccuracy": null,
  "arrayType": null,
  "arraySize": 2,
  "mustFill": true,
  "default": null,
  "num": 1,
  "definition": null,
  "opration": "",
  "dataTypeTitle": "position(位置)"
}, {
  "id": 163606,
  "code": null,
  "name": "photoFiles",
  "title": "电站图片",
  "sn": 6,
  "dataType": {"id": 163251, "code": null, "name": "image", "title": "image(图片)", "sn": 9, "activity": true, "baseType": false},
  "type": 1,
  "symbol": null,
  "validationType": null,
  "unit": null,
  "boolValues": null,
  "enumValues": null,
  "min": null,
  "max": null,
  "step": null,
  "length": 256,
  "timeAccuracy": null,
  "arrayType": null,
  "arraySize": null,
  "mustFill": true,
  "default": null,
  "num": 2,
  "definition": null,
  "opration": "",
  "dataTypeTitle": "image(图片)"
}, {
  "id": 163603,
  "code": null,
  "name": "power",
  "title": "额定功率",
  "sn": 3,
  "dataType": {"id": 159890, "code": null, "name": "int32", "title": "int32(整数型)", "sn": 1, "activity": true, "baseType": true},
  "type": 1,
  "symbol": null,
  "validationType": null,
  "unit": {"id": 159989, "code": null, "name": "kW", "title": "千瓦", "sn": 1, "activity": true},
  "boolValues": null,
  "enumValues": null,
  "min": 1,
  "max": 9999999,
  "step": 1,
  "length": null,
  "timeAccuracy": null,
  "arrayType": null,
  "arraySize": null,
  "mustFill": true,
  "default": null,
  "num": 3,
  "definition": null,
  "opration": "",
  "dataTypeTitle": "int32(整数型)"
}, {
  "id": 163604,
  "code": null,
  "name": "address",
  "title": "电站地址",
  "sn": 4,
  "dataType": {"id": 159893, "code": null, "name": "text", "title": "text(字符串)", "sn": 4, "activity": true, "baseType": true},
  "type": 1,
  "symbol": null,
  "validationType": null,
  "unit": null,
  "boolValues": null,
  "enumValues": null,
  "min": null,
  "max": null,
  "step": null,
  "length": 128,
  "timeAccuracy": null,
  "arrayType": null,
  "arraySize": null,
  "mustFill": false,
  "default": null,
  "num": 4,
  "definition": null,
  "opration": "",
  "dataTypeTitle": "text(字符串)"
}, {
  "id": 164431,
  "code": null,
  "name": "title",
  "title": "电站名称",
  "sn": 1,
  "dataType": {"id": 159893, "code": null, "name": "text", "title": "text(字符串)", "sn": 4, "activity": true, "baseType": true},
  "type": 1,
  "symbol": null,
  "validationType": null,
  "unit": null,
  "boolValues": null,
  "enumValues": null,
  "min": null,
  "max": null,
  "step": null,
  "length": 64,
  "timeAccuracy": null,
  "arrayType": null,
  "arraySize": null,
  "mustFill": true,
  "default": null,
  "num": 5,
  "definition": null,
  "opration": "",
  "dataTypeTitle": "text(字符串)"
}, {
  "id": 166635,
  "code": null,
  "name": "capacity",
  "title": "建设规模",
  "sn": 2,
  "dataType": {"id": 159890, "code": null, "name": "int32", "title": "int32(整数型)", "sn": 1, "activity": true, "baseType": true},
  "type": 1,
  "symbol": null,
  "validationType": null,
  "unit": {"id": 162094, "code": null, "name": "kVA", "title": "千伏安", "sn": 17, "activity": true},
  "boolValues": null,
  "enumValues": null,
  "min": 1,
  "max": 9999999,
  "step": 1,
  "length": null,
  "timeAccuracy": null,
  "arrayType": null,
  "arraySize": null,
  "mustFill": true,
  "default": null,
  "num": 6,
  "definition": null,
  "opration": "",
  "dataTypeTitle": "int32(整数型)"
}, {
  "id": 163607,
  "code": null,
  "name": "operationTime",
  "title": "实际投产时间",
  "sn": 7,
  "dataType": null,
  "type": 1,
  "symbol": null,
  "validationType": null,
  "unit": null,
  "boolValues": null,
  "enumValues": null,
  "min": null,
  "max": null,
  "step": null,
  "length": null,
  "timeAccuracy": null,
  "arrayType": null,
  "arraySize": null,
  "mustFill": false,
  "default": null,
  "num": 7,
  "definition": null,
  "opration": ""
}, {
  "id": 163608,
  "code": null,
  "name": "notes",
  "title": "备注",
  "sn": 8,
  "dataType": {"id": 159893, "code": null, "name": "text", "title": "text(字符串)", "sn": 4, "activity": true, "baseType": true},
  "type": 1,
  "symbol": null,
  "validationType": null,
  "unit": null,
  "boolValues": null,
  "enumValues": null,
  "min": null,
  "max": null,
  "step": null,
  "length": 256,
  "timeAccuracy": null,
  "arrayType": null,
  "arraySize": null,
  "mustFill": false,
  "default": null,
  "num": 8,
  "definition": null,
  "opration": "",
  "dataTypeTitle": "text(字符串)"
}]

export const mock_StationBasicInfo = {
  title: 'mock station',
  stationType: {
    id: 1,
    title: 'wer'
  },
  photoFiles: ['aa']
}
export const mock_StationManageInfo = {
  operator: {id: 1, title: 'a'},
  maintenance: {id: 2, title: 'b'},
  finalUser: {id: 3, title: 'c'}
}
export const mock_StationEnergyList = {
  energyUnit: [{num: 1}]
}
export const mock_StationPriceInfo = {
  costId: 1,
  generatorId: 1
}
export const mock_HistoryList = {
  results: {
    results: [{}],
    totalCount: 20
  }
}
